### PR TITLE
Support for curve-zmq

### PR DESCRIPTION
**Pull request by niamster**

### CODE REVIEW

**Comment by digitalextremist** [comment]
Awesome. Should the `.deb` files maybe be part of `culture/debs` like we have `culture/gems` right now?

**Comment by niamster** [comment]
@digitalextremist these debs are actually dcell-specific so I don't see why anybody else want to have them.
I would really prefer to get rid of them as they should be only used on travis(recent ubuntu and debian SID should have them). In Arch it's already there since ages. 
In practice if a distro doesn't have have appropriate version of libzmq it must be build manually.
I've tried to build 'em on travis but it's takes too much time. So in the end I prebuilt these debs myself.

**Comment by digitalextremist** [comment]
Ah! I wondered. I understand/agree on all points.

**Comment by digitalextremist** [comment]
Exciting to see CurveZMQ coming in. I abandoned my branch a long time ago when you mentioned changes coming to the library. So is the library settled now?

**Comment by niamster** [comment]
Yes, I believe so. Next step would be to add stats(for monitoring and load balancing). 
Also it would be nice to get rid of registries(too many of them!) and build smth on top of DCell itself.
Maybe smth like Raft but in fact DCell doesn't require that tight synchronization and also I don't like the idea of a single master.

**Comment by digitalextremist** [comment]
I'm itching to use DCell+CZMQ myself, so don't worry about superstructure coming in over it. Especially if we can thin-out the registries. Any thoughts on using protobuf or similar for data exchange?

**Comment by niamster** [comment]
You want to have a server written in C?
Well, I was thinking myself about that.

**Comment by tarcieri** [comment]
@niamster you could use an eventually consistent gossip protocol ala `riak_core` or Serf (i.e. SWIM)

**Comment by tarcieri** [comment]
> Any thoughts on using protobuf or similar for data exchange?

He already switched to msgpack, which is a nice fit for a dynamic language like Ruby

**Comment by digitalextremist** [comment]
@tarcieri, ah -- I fell out of the loop on that one. Congratz @niamster.

How's Japan going, are you still there @tarcieri?

**Comment by tarcieri** [comment]
I'm back in the US now

**Comment by digitalextremist** [comment]
msgpack looks great. Excited to check that out further.

I hope the trip was great.

Just signed a two-year lease on a new lab, once I settle in, I'm planning to head up that way.

**Comment by Asmod4n** [comment]
(currently writing a actor for czmq in c which does raft internally and exposes a REST "API")

**Comment by Asmod4n** [comment]
(Its using http://rfc.zeromq.org/spec:40/XRAP for REST)

**Comment by shadoi** [comment]
@Asmod4n wow, this sounds very interesting, can you share anything yet?

**Comment by Asmod4n** [comment]
@shadoi nothing useable yet: https://github.com/Asmod4n/craft, logic is in src/craft.c.

**Comment by niamster** [comment]
I'm going to merge this and close #62 if there are no objections here.

**Pull request merged**
