### PR TITLE
An experimental support of msgpack as Marshalling backend

### PR DESCRIPTION
**Pull request by niamster**

### CODE REVIEW

**Comment by niamster** [comment]
Note this drops jruby support until msgpack-jruby is properly merged into official msgpack with all features.

**Comment by Asmod4n** [comment]
msgpack-jrubx just got merged into msgpack-ruby ☺

**Comment by niamster** [comment]
Spec with jruby-head doesn't pass but it's not tested by msgpack so I'm about to merge this if everybody agree.

**Comment by tarcieri** [comment]
Nice! :+1:

**Pull request merged**
